### ISSUE TITLE
Install documentation

### ISSUE THREAD

**Issue by insp63** [hcengineering/huly-selfhost#121]
Friends, share the configuration of how you set up the connection between HULU and Love Service.
There have already been many themes, but there is no single setting. 
The code doesn't work in the README: in the browser, HULU is trying to log out to the server http://love:8096 naturally, there is no such address, it is an internal address, then why does specifying the LIVEKIT_HOST address not work?
There is also a question about telegram, why is there no request after entering the phone?
HULU is deployed on a server with an external IP of 188.190xxxx. This IP is configured via ./setup.sh

![Image](https://github.com/user-attachments/assets/cbf5757e-77fe-4416-acb7-9815d59993d8)

![Image](https://github.com/user-attachments/assets/eaa3f8f8-9afb-4aa8-9f4e-8339f7b1509f)

![Image](https://github.com/user-attachments/assets/bb26cef3-89ea-4e86-b383-2cc17ecd81ce)

**Comment by aonnikov** [comment]
@insp63 thanks for reporting this. Indeed, this is a bug in the README.md. The LOVE_ENDPOINT should be the URL of the `love` container. Current `compose.yml` already contains proper value: https://github.com/hcengineering/huly-selfhost/blob/main/compose.yml#L119
If you are not using nginx, then adjust the value according to your setup, i.e.  for you it can be `http://188.190.xxx.xxx:8096`

**Comment by insp63** [comment]
It definitely shouldn't be like this ((

![Image](https://github.com/user-attachments/assets/1758fa77-f038-458f-bae4-ad5492b86c0e)

![Image](https://github.com/user-attachments/assets/e369f4f1-3e21-4b7d-a1bf-07af715fb81d)

**Comment by insp63** [comment]
> [@insp63](https://github.com/insp63) thanks for reporting this. Indeed, this is a bug in the README.md. The LOVE_ENDPOINT should be the URL of the `love` container. Current `compose.yml` already contains proper value: https://github.com/hcengineering/huly-selfhost/blob/main/compose.yml#L119 If you are not using nginx, then adjust the value according to your setup, i.e. for you it can be `http://188.190.xxx.xxx:8096`

Removed the extra lines, but other errors

**Comment by aonnikov** [comment]
So based on your screenshot I see that there are two issues:
1. 404 error when trying to POST `http://.../_love/getToken` 
2. Lack of error handling on our side, as a result we put some garbage as LiveKit token

Please check that love container is accessible by this address, it should solve the problem.

**Comment by insp63** [comment]
> Итак, основываясь на вашем скриншоте, я вижу, что есть две проблемы:
> 
> 1. Ошибка 404 при попытке POST`http://.../_love/getToken`
> 2. Отсутствие обработки ошибок на нашей стороне, в результате чего мы помещаем какой-то мусор в качестве токена LiveKit
> 
> Пожалуйста, проверьте, доступен ли контейнер любви по этому адресу, это должно решить проблему.

![Image](https://github.com/user-attachments/assets/5c9fa4ed-1cbf-4c10-b335-2b9cb84d82a5)

**Comment by insp63** [comment]
> Итак, основываясь на вашем скриншоте, я вижу, что есть две проблемы:
> 
> 1. Ошибка 404 при попытке POST`http://.../_love/getToken`
> 2. Отсутствие обработки ошибок на нашей стороне, в результате чего мы помещаем какой-то мусор в качестве токена LiveKit
> 
> Пожалуйста, проверьте, доступен ли контейнер любви по этому адресу, это должно решить проблему.

![Image](https://github.com/user-attachments/assets/ff1b4564-6195-477c-91f2-c1b1b783f4d9)

**Comment by DenisBessa** [comment]
I had the same issue.

Here's the trick: in the `front` container, all URLs should point to the **public** URL, accessible from the browser.

For all other containers, the URLs can be internal, in the Docker network.

Here is an example:

The `front` container:
```
  front:
    image: hardcoreeng/front:${HULY_VERSION}
    environment:
      - SERVER_PORT=8080
      - SERVER_SECRET=${SECRET}
      - LOVE_ENDPOINT=http${SECURE:+s}://${HOST_ADDRESS}/_love
      - ACCOUNTS_URL=http${SECURE:+s}://${HOST_ADDRESS}/_accounts
      - REKONI_URL=http${SECURE:+s}://${HOST_ADDRESS}/_rekoni
      - CALENDAR_URL=http${SECURE:+s}://${HOST_ADDRESS}/_calendar
      - GMAIL_URL=http${SECURE:+s}://${HOST_ADDRESS}/_gmail
      - TELEGRAM_URL=http${SECURE:+s}://${HOST_ADDRESS}/_telegram
      - STATS_URL=http${SECURE:+s}://${HOST_ADDRESS}/_stats
      - AI_URL=http${SECURE:+s}://${HOST_ADDRESS}/_aibot
      - UPLOAD_URL=/files
      - ELASTIC_URL=http://elastic:9200
      - COLLABORATOR_URL=ws${SECURE:+s}://${HOST_ADDRESS}/_collaborator
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - DB_URL=mongodb://mongodb:27017
      - MONGO_URL=mongodb://mongodb:27017
      - TITLE=${TITLE:-Huly Self Host}
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE:-en}
      - LAST_NAME_FIRST=${LAST_NAME_FIRST:-true}
      - DESKTOP_UPDATES_CHANNEL=selfhost
    restart: unless-stopped
```

The `love` container:
```
  love:
    image: hardcoreeng/love:${HULY_VERSION}
    container_name: love
    expose:
      - 8096
    env_file:
      - ./.env
    environment:
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - SECRET=${SECRET}
      - ACCOUNTS_URL=http://account:3000
      - DB_URL=mongodb://mongodb:27017
      - MONGO_URL=mongodb://mongodb:27017
      - STORAGE_PROVIDER_NAME=minio
      - PORT=8096
    restart: unless-stopped
```

The `nginx.conf` file
```
server {
    listen 80;
    server_name _;
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://front:8080;
    }

    location /_accounts {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        rewrite ^/_accounts(/.*)$ $1 break;
        proxy_pass http://account:3000/;
    }

    location /_collaborator {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        rewrite ^/_collaborator(/.*)$ $1 break;
        proxy_pass http://collaborator:3078/;
    }

    location /_transactor {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        rewrite ^/_transactor(/.*)$ $1 break;
        proxy_pass http://transactor:3333/;
    }

    location ~ ^/eyJ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://transactor:3333;
    }

    location /_rekoni {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        rewrite ^/_rekoni(/.*)$ $1 break;
        proxy_pass http://rekoni:4004/;
    }

    location /_stats {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        rewrite ^/_stats(/.*)$ $1 break;
        proxy_pass http://stats:4900/;
    }

    location /_love {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        rewrite ^/_love(/.*)$ $1 break;
        proxy_pass http://love:8096;
    }

    location /_aibot {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        rewrite ^/_aibot(/.*)$ $1 break;
        proxy_pass http://aibot:4010;
    }
}
```
