### ISSUE TITLE
Error: Signature verification failed

### ISSUE THREAD

**Issue by dodancs** [hcengineering/huly-selfhost#123]
Hey,
I just tried to install Huly self-hosted, and when I check out the compose logs, I see this from the stats container over and over:

```
stats-1         | Error: Signature verification failed
stats-1         |     at jwt_decode (/usr/src/app/bundle.js:79471:17)
stats-1         |     at decodeToken (/usr/src/app/bundle.js:79612:50)
stats-1         |     at /usr/src/app/bundle.js:102175:59
stats-1         |     at dispatch (/usr/src/app/bundle.js:91138:36)
stats-1         |     at /usr/src/app/bundle.js:101863:20
stats-1         |     at dispatch (/usr/src/app/bundle.js:91138:36)
stats-1         |     at /usr/src/app/bundle.js:91130:16
stats-1         |     at dispatch (/usr/src/app/bundle.js:101867:35)
stats-1         |     at dispatch (/usr/src/app/bundle.js:91138:36)
stats-1         |     at bodyParser (/usr/src/app/bundle.js:101104:15)
```

**Comment by aonnikov** [comment]
Looks like misconfiguration, there probably an incorrect secret configured in the stats container.

**Comment by MilanovaSmile** [comment]
@aonnikov I have the same problem. Here are the statistic server settings, what could be wrong here?

```
stats:
    image: hardcoreeng/stats:${HULY_VERSION}
    environment:
      - PORT=4900
      - SERVER_SECRET=${SECRET}
    restart: unless-stopped
```
