### ISSUE TITLE
Invalid redirect URI github oauth

### ISSUE THREAD

**Issue by bursao** [hcengineering/huly-selfhost#135]
Hi, im trying to configure github oauth since i discovered cant configure email for log in.
Well, i did create the github OAuth app, and put variables in docker-compose.yaml, but im having error on the title:

![Image](https://github.com/user-attachments/assets/c7aee892-e5aa-405b-b2df-f156603d4166)

OAuth app config:

Homepage URL: https://huly.mydomain.com
Authorization callback URL: https://huly.mydomain.com/auth/github/callback

docker-compose.yml conf:

```
account:
    image: hardcoreeng/account:v0.6.377
    environment:
      - SERVER_PORT=3000
      - SERVER_SECRET=secret
      - DB_URL=mongodb://mongodb:27017
      - TRANSACTOR_URL=ws://transactor:3333;wss://huly.mydomain.com:3333
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
#      - FRONT_URL=http://front:8080
      - FRONT_URL=https://huly.mydomain.com
      - STATS_URL=http://stats:4900
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://account:3000
      - ACCOUNT_PORT=3000
      - GITHUB_CLIENT_ID=***********
      - GITHUB_CLIENT_SECRET=************
      - GITHUB_REDIRECT_URI=https://huly.mydomain.com/auth/github/callback

front:
    image: hardcoreeng/front:v0.6.377
    environment:
      - SERVER_PORT=8080
      - SERVER_SECRET=secret
      - ACCOUNTS_URL=https://huly.mydomain.com/accounts
```
