### ISSUE TITLE
video/audio chat is not working on selfhosted with traefik

### ISSUE THREAD

**Issue by deviljutt** [hcengineering/huly-selfhost#37]
traefik/template-compose.yaml

i am using traefik to start the self hosted server i don't see voice chat icon on top. can anyone confirm if this issue is there ?

![image](https://github.com/user-attachments/assets/6e957d99-3779-4f7d-8c96-b9bd6472f584)

[docker-compose.txt](https://github.com/user-attachments/files/17074361/docker-compose.txt)

**Comment by aonnikov** [comment]
Hey! Default configuration does not contain office voice/video calls. Video chats are based on [LiveKit](https://livekit.io) so if you LiveKit Cloud account, you can set up the calls.

**Comment by saif-malik-01** [comment]
@aonnikov, how can I setup the livekit account with self host nginx?

**Comment by aonnikov** [comment]
> @aonnikov, how can I setup the livekit account with self host nginx?

@saif-malik-01 we are using [Livekit Cloud](https://cloud.livekit.io/), you will need to setup `love` container:

```
love:
    image: hardcoreeng/love:${HULY_VERSION}
    links:
      - mongodb
      - minio
    ports:
      - 8096:8096
    environment:
      - PORT=8096
      - SECRET=${HULY_SECRET}
      - ACCOUNTS_URL=http://${SERVER_ADDRESS}:3000
      - MONGO_URL=mongodb://mongodb:27017
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - LIVEKIT_HOST=...
      - LIVEKIT_API_KEY=...
      - LIVEKIT_API_SECRET=...
    restart: unless-stopped
```

and in the front service you will need to add couple of env variables:
```
    - LIVEKIT_WS=...
    - LOVE_ENDPOINT=http://love:8096
```

The last three variables you can obtain in your Livekit Cloud account once you set it up.
