### ISSUE TITLE
transactor container has error:  Please provide ELASTIC_INDEX_NAME

### ISSUE THREAD

**Issue by fama** [hcengineering/huly-selfhost#5]
After the update to v0.6.228a (also tried the latest), I have been getting an error in the transactor container 

```
 Please provide ELASTIC_INDEX_NAME
```

The  `elastic` container is running without problems and it connects over docker networking.  (this was all working prior to update)

```yaml
  transactor:
    image: hardcoreeng/transactor:v0.6.228a
    links:
      - mongodb
      - elastic
      - minio
      - huly-rekoni
      - account
    ports:
      - 3333:3333
    environment:
      - SERVER_PORT=3333
      - SERVER_SECRET=secret
      - SERVER_CURSOR_MAXTIMEMS=30000
      - ELASTIC_URL=http://elastic:9200
      - MONGO_URL=mongodb://mongodb:27017
      - METRICS_CONSOLE=false
      - METRICS_FILE=metrics.txt
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - REKONI_URL=http://huly-rekoni:4004
      - FRONT_URL=https://huly.${DOMAIN}
      - SERVER_PROVIDER=ws
      - ACCOUNTS_URL=http://account:3000
      - LAST_NAME_FIRST=true
    restart: unless-stopped
```
