### ISSUE TITLE
Unknown error: failed to fetch

### ISSUE THREAD

**Issue by shanzez** [hcengineering/huly-selfhost#99]
Hello! We're excited to try Huly out.  I'm having some issues, I believe, with my nginx configuration.  We're getting:
![image](https://github.com/user-attachments/assets/837e7116-9fce-4194-8a3c-c20774b4883f)

Our setup:

We're running nginx in a separate container, but on the same external docker network.  I did this so I would just be able to route everything via the same nginx instance on our test machine.  We have two other applications using this setup successfully.

We're able to get to huly.<domain>, but cannot login or create accounts.  Here is the addition I made to our nginx.conf for huly:
```
    server {
        listen 80;
        server_name huly.<our domain>;
        return 301 https://$server_name$request_uri;
    }

    server {
        listen 3000 ssl;
        server_name huly.<our domain>;

        ssl_certificate /etc/nginx/ssl/huly.crt;
        ssl_certificate_key /etc/nginx/ssl/huly.key;

        location / {
            proxy_pass http://account:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

    }

    server {
        listen 443 ssl;

        server_name huly.<our domain>;

        ssl_certificate /etc/nginx/ssl/huly.crt;
        ssl_certificate_key /etc/nginx/ssl/huly.key;

        location / {
            proxy_pass http://front:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        client_max_body_size 200M;
    }
```

And the docker compose file for the account container:
```
  account:
    image: hardcoreeng/account:v0.6.333
    ports:
      - 3000:3000
    environment:
      - SERVER_PORT=3000
      - SERVER_SECRET=<removed> 
      - DB_URL=mongodb://mongodb:27017
      - TRANSACTOR_URL=ws://transactor:3333;ws://huly.<our domain>:3333
      - STORAGE_CONFIG=minio|minio?accessKey=<removed>&secretKey=<removed>
      - FRONT_URL=http://front:8080
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=https://huly.<our domain>:3000
      - ACCOUNT_PORT=3000
    restart: unless-stopped
    networks:
      - sharednet
```
